# Generated by Django 3.2 on 2022-04-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20220425_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='upazilla',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='address',
            name='thana',
        ),
    ]
