# Generated by Django 3.2 on 2022-04-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20220425_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='mrp_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
